### ISSUE TITLE
Move to Rspec for testing

### ISSUE THREAD

**Issue by danmelton** [codeforamerica/shortstack#1]
Install necessary gems and test files

**Comment by sferik** [comment]
We should use bundler to manage gem dependencies.

**Comment by sferik** [comment]
I've migrated a bunch of projects to Rspec. Here's an example commit: https://github.com/pengwynn/octokit/commit/dd868886c0eac403020685d462935dda3871fe65

**Comment by danmelton** [comment]
agreed.
