### ISSUE TITLE
Users should be prompted to assign themselves a screen name upon signup

### ISSUE THREAD

**Issue by scottsil** [codeforamerica/shortstack#20]

**Comment by rockymeza** [comment]
Have you changed your screenname?  There is an edit Profile link at the top of the page to set your display name.

Aside:
It's nice that you can change your screenname, but you shouldn't necessarily have to.  For a future iteration, the screenname should be set to something better than 'changeme'.

**Comment by scottsil** [comment]
That would explain. I'm changing this request to have users pick a screen name upon login. It is not obvious that users must edit their profile for this to display not as "changeme"...

**Comment by rockymeza** [comment]
fixed
