### ISSUE TITLE
Hook in gravatar for profiles with email addresses

### ISSUE THREAD

**Issue by danmelton** [codeforamerica/shortstack#9]

**Comment by danmelton** [comment]
note, we'll need to think about how github/facebook/twitter/linkedin fits into this

**Comment by rockymeza** [comment]
maybe we should give users the ability to choose which picture they use in their settings.

We could default to a gravatar, people might be less than enthused if we automatically pull in their facebook images... then again they did sign in with facebook.

**Comment by danmelton** [comment]
that sounds good to me
